/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';




export namespace Components {

  interface LedInput {
    'first': string;
    'last': string;
    'mask': string;
    'maskPlaceholder': string;
    'placeholder': string;
    'required': boolean;
  }
  interface LedInputAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
    'mask'?: string;
    'maskPlaceholder'?: string;
    'placeholder'?: string;
    'required'?: boolean;
  }
}

declare global {
  interface StencilElementInterfaces {
    'LedInput': Components.LedInput;
  }

  interface StencilIntrinsicElements {
    'led-input': Components.LedInputAttributes;
  }


  interface HTMLLedInputElement extends Components.LedInput, HTMLStencilElement {}
  var HTMLLedInputElement: {
    prototype: HTMLLedInputElement;
    new (): HTMLLedInputElement;
  };

  interface HTMLElementTagNameMap {
    'led-input': HTMLLedInputElement
  }

  interface ElementTagNameMap {
    'led-input': HTMLLedInputElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
